import { EventsProvider } from '@/components/EventsProvider';
import './globals.css';
import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import Modals from '@/widgets/Modals/Modals';
import { StorageProvider } from '@/components/StorageProvider';

export const metadata: Metadata =
{
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter(
{
    subsets: ['latin'],
    weight: ['400', '500', '700'],
});

export default function RootLayout({children,}: 
    Readonly<{children: React.ReactNode;}>) 
{
    return (
        <html lang="ru" className={inter.className}>
            <body>
                <EventsProvider>
                <StorageProvider>
                    <Modals />
                    {children}
                </StorageProvider>
                </EventsProvider>
            </body>
        </html>
    );
}
